name: tagging_flutter
description: Flutter widgets for anchored tagging flows.
publish_to: 'none'
version: 0.1.0
repository: https://github.com/minchanpark/tagging_flutter

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  tagging_core:
    git:
      url: https://github.com/minchanpark/tagging_core.git
      ref: v0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
